blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("detail/<slug:slug>", views.post_detaile, name="detail"),
    path("list", views.ArticleListView.as_view(), name="list"),
    path("category/<int:pk>", views.category_detail, name="category_detail"),
    path("search/", views.search, name="search_articles"),
    path("contact_us/", views.MessageView.as_view(), name="contact_us"),
    path("users", views.UserList.as_view(), name="user_list"),
    path("red", views.HomePageRedirect.as_view(), name="redirect"),
    path("messages", views.MessagesListView.as_view(), name="message_list"),
    path("message/edit/<int:pk>", views.MessageUpdateView.as_view(), name="message_edit"),
    path("message/delete/<int:pk>", views.MessageDeleteView.as_view(), name="message_delete"),
    path("archive", views.ArchiveIndexArticleView.as_view(), name="archive"),
    path("archive/<int:year>", views.YearArchiveArticleView.as_view(), name="archive_year"),
    path("like/<slug:slug>/<int:pk>", views.like, name="like"),
]

standblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("", include("account.urls")),
    path("article/", include("blog.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.html import format_html
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name="عنوان")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"


class Article(models.Model):
    auther = models.ForeignKey(User, on_delete=models.CASCADE, related_name="articles", verbose_name="نویسنده")
    category = models.ManyToManyField(Category, related_name="articles", verbose_name="موضوع")
    title = models.CharField(max_length=70, verbose_name="تایتل")
    body = models.TextField(verbose_name="متن")
    image = models.ImageField(upload_to="images/article", blank=True, null=True, verbose_name="عکس")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=False, verbose_name="وضعیت")
    slug = models.SlugField(null=True, blank=True, unique=True, verbose_name="اسلاگ ")
    pub_date = models.DateTimeField(default=timezone.now())

    class Meta:
        ordering = ("-created",)
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save()

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug": self.slug})

    # def show_image(self):
    #     return format_html(f'<img src="{self.image.url}" width="30px" height="30px" >')

    def __str__(self):
        return f"{self.title} - {self.body[:30]}"


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments", verbose_name="مقاله")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments", verbose_name="کاربر")
    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="replies", verbose_name="در جواب")
    body = models.TextField(verbose_name="متن پیام")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[:50]

    class Meta:
        verbose_name = "نظر"
        verbose_name_plural = "نظرات"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="likes")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="likes")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.article.title}"

    class Meta:
        verbose_name = "لایک"
        verbose_name_plural = "لایک ها"


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name="تایتل")
    text = models.TextField(verbose_name="متن پیام")
    email = models.EmailField(verbose_name="ایمبل")
    age = models.IntegerField(default=0, verbose_name="سن")
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    date = models.DateTimeField(default=timezone.now(), verbose_name="تاریخ")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "پیام"
        verbose_name_plural = "پیام ها"




    # class Meta:
    #     verbose_name = "لایک"
    #     verbose_name_plural = "لایک ها"
    #     ordering = ("-created_at",)

blog/forms.py
from django import forms
from django.core.validators import ValidationError
from blog.models import Message


class ContactUsForm(forms.Form):
    BIRTH_YEAR_CHOICES = ["2000", "2003", "2007"]
    FAVORITE_COLOR_CHOICES = [
        ("blue", "Blue"),
        ("green", "Green"),
        ("red", "Red"),
        ("black", "Black")
    ]
    name = forms.CharField(max_length=10, label="your name")
    text = forms.CharField(max_length=10, label="your massage")
    birth_year = forms.DateField(widget=forms.DateTimeInput(attrs={"class": "form-control"}))
    color = forms.ChoiceField(choices=FAVORITE_COLOR_CHOICES)
    numbers = forms.ImageField(widget=forms.NumberInput())

    def clean(self):
        name = self.cleaned_data.get("name")
        text = self.cleaned_data.get("text")
        if name == text:
            raise ValidationError("name and text are same", code="name_text_same")


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        exclude = ("email",)
        widgets = {
            "title": forms.TextInput(attrs={
                "class": "form-control",
                "placeholder": "enter your text",
                "style": "max-width: 300px;"
            }),
            "text": forms.Textarea(attrs={
                "class": "form-control",
            }),
        }

blog/views.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from .models import Article, Category, Comment, Message, Like
from django.core.paginator import Paginator
from .forms import ContactUsForm, MessageForm
from django.views.generic.base import View, TemplateView, RedirectView
from django.views.generic import ListView, DetailView, FormView, CreateView, UpdateView, DeleteView, ArchiveIndexView, YearArchiveView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from . mixins import LoginBlogRequiredMixin


def post_detaile(request, slug):
    article = get_object_or_404(Article, slug=slug)
    if request.method == "POST":
        parent_id = request.POST.get("parent_id")
        body = request.POST.get("body")
        Comment.objects.create(body=body, article=article, user=request.user, parent_id=parent_id)
    return render(request, template_name="blog/article_details.html", context={"article": article})


def article_list(request):
    articles = Article.objects.all()
    page_number = request.GET.get("page")
    paginator = Paginator(articles, 2)
    object_list = paginator.get_page(page_number)
    return render(request, template_name="blog/article_list.html", context={"articles": object_list})


def category_detail(request, pk):
    category = get_object_or_404(Category, id=pk)
    articles = category.articles.all()
    return render(request, template_name="blog/article_list.html", context={"articles": articles})


def search(request):
    q = request.GET.get("q")
    articles = Article.objects.filter(title__contains=q)
    page_number = request.GET.get("page")
    print(page_number)
    paginator = Paginator(articles, 2)
    object_list = paginator.get_page(page_number)
    return render(request, template_name="blog/article_list.html", context={"articles": object_list})


def contact_us(request):
    if request.method == "POST":
        form = MessageForm(data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance += 5
            instance.save()
    else:
        form = MessageForm()
    return render(request, template_name="blog/contact_us.html", context={"form": form})


# class ListView(View):
#     queryset = None
#     template_name = None
#
#     def get(self, request):
#         return render(request, self.template_name, context={"object_list": self.queryset})

class HomePageRedirect(RedirectView):
    # url = "/"
    pattern_name = "blog:list"


class ArticleList(TemplateView):
    pass


class UserList(ListView):
    queryset = User.objects.all()
    template_name = "blog/user_list.html"


class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.likes.filter(article__slug=self.object.slug, user__id=self.request.user.id).exists():
            context["is_liked"] = True
        else:
            context["is_liked"] = False
        return context


# LoginRequiredMixin
class ArticleListView(LoginBlogRequiredMixin, ListView):
    model = Article
    context_object_name = "articles"
    paginate_by = 2


class ContactUsView(FormView):
    template_name = "blog/contact_us.html"
    form_class = MessageForm
    success_url = reverse_lazy("home_app:home")

    def form_valid(self, form):
        from_data = form.cleaned_data
        Message.objects.create(**from_data)
        return super().form_valid(form)


class MessageView(CreateView):
    model = Message
    fields = ("title", "text", "age", "date")
    success_url = reverse_lazy("home_app:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["messages"] = Message.objects.all()
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.email = self.request.user.email
        instance.save()
        return super().form_valid(form)

    def get_success_url(self):
        print(self.object)
        return super(MessageView, self).get_success_url()


class MessagesListView(ListView):
    model = Message


class MessageUpdateView(UpdateView):
    model = Message
    fields = ("title", "text", "age")
    template_name_field = "_update_form"
    success_url = reverse_lazy("blog:message_list")


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy("blog:message_list")


class ArchiveIndexArticleView(ArchiveIndexView):
    model = Article
    date_field = "updated"


class YearArchiveArticleView(YearArchiveView):
    model = Article
    date_field = "pub_date"
    make_object_list = True
    allow_empty = True
    template_name = "blog/article_archive_year.html"


def like(request, slug, pk):
    try:
        like = Like.objects.get(article__slug=slug, user__id=request.user.id)
        like.delete()
        return JsonResponse({"response": "unliked"})
    except:
        Like.objects.create(article_id=pk, user_id=request.user.id)
        return JsonResponse({"response": "liked"})

blog/templates/blog/article.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Article List
{% endblock %}
{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Recent Posts</h4>
                <h2>Our Recent Blog Entries</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    
    <!-- Banner Ends Here -->

{#    <section class="call-to-action">#}
{#      <div class="container">#}
{#        <div class="row">#}
{#          <div class="col-lg-12">#}
{#            <div class="main-content">#}
{#              <div class="row">#}
{#                <div class="col-lg-8">#}
{#                  <span>Stand Blog HTML5 Template</span>#}
{#                  <h4>Creative HTML Template For Bloggers!</h4>#}
{#                </div>#}
{#                <div class="col-lg-4">#}
{#                  <div class="main-button">#}
{#                    <a href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </section>#}


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">

                {% for article in articles %}
                <div class="col-lg-6">
                  <div class="blog-post">
                    {% if article.image %}
                    <div class="blog-thumb">
                      <img src="{{ article.image.url }}" alt="">
                    </div>
                    {% else %}
                    <div class="blog-thumb">
                      <img src="{% static "images/banner-item-01.jpg" %}" alt="">
                    </div>
                    {% endif %}
                    <div class="down-content">
                      <span>{{ article.category.all.first }}</span>
                      <a href="{{ article.get_absolute_url }}"><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.auther.username }}</a></li>
                        <li><a href="#">{{ article.created }}</a></li>
                        <li><a href="#">12 Comments</a></li>
                      </ul>
                      <p>{{ article.body | truncatewords:10 }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-lg-12">
                            <ul class="post-tags">
                              <li><i class="fa fa-tags"></i></li>
                              <li><a href="#">Best Templates</a>,</li>
                              <li><a href="#">TemplateMo</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}

                <div class="col-lg-12">
                  <ul class="page-numbers">
                    <li><a href="#">1</a></li>
                    <li class="active"><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          {% include "includes/sidebar.html" %}
        </div>
      </div>
    </section>

    
{% endblock %}

blog/templates/blog/article_archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for article in latest %}
        <li>{{ article.updated }}: {{ article.title }}</li>
    {% endfor %}
</body>
</html>

blog/templates/blog/article_archive_year.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <ul>
        {% for date in date_list %}
            <li>{{ date|date }}</li>
        {% endfor %}
    </ul>

    <div>
        <h1>All Articles for {{ year|date:"Y" }}</h1>
        {% for obj in object_list %}
            <p>
            {{ obj.title }} - {{ obj.pub_date|date:"F j, Y" }}
            </p>
        {% endfor %}
    </div>
</body>
</html>

blog/templates/blog/article_details.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Post Detail
{% endblock %}
{% block content %}

    <!-- Page Content -->
    <!-- Banner Starts Here -->
    <div class="heading-page header-text">
      <section class="page-heading">
        <div class="container">
          <div class="row">
            <div class="col-lg-12">
              <div class="text-content">
                <h4>Article Details</h4>
                <h2>{{ article.title }}</h2>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- Banner Ends Here -->

{#    <section class="call-to-action">#}
{#      <div class="container">#}
{#        <div class="row">#}
{#          <div class="col-lg-12">#}
{#            <div class="main-content">#}
{#              <div class="row">#}
{#                <div class="col-lg-8">#}
{#                  <span>Stand Blog HTML5 Template</span>#}
{#                  <h4>Creative HTML Template For Bloggers!</h4>#}
{#                </div>#}
{#                <div class="col-lg-4">#}
{#                  <div class="main-button">#}
{#                    <a rel="nofollow" href="https://templatemo.com/tm-551-stand-blog" target="_parent">Download Now!</a>#}
{#                  </div>#}
{#                </div>#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </section>#}


    <section class="blog-posts grid-system">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">
            <div class="all-blog-posts">
              <div class="row">
                <div class="col-lg-12">
                  <div class="blog-post">
                    {% if article.image %}
                    <div class="blog-thumb">
                      <img src="{{ article.image.url }}" alt="">
                    </div>
                    {% else %}
                    <div class="blog-thumb">
                      <img src="{% static "images/banner-item-01.jpg" %}" alt="">
                    </div>
                    {% endif %}
                    <div class="down-content">
                      <span>{{ article.category.all.first }}</span>
                      <a href="article_details.html"><h4>{{ article.title }}</h4></a>
                      <ul class="post-info">
                        <li><a href="#">{{ article.auther.username }}</a></li>
                        <li><a href="#">{{ article.created }}</a></li>
                        <li><a href="#">10 Comments</a></li>
                      </ul>
                      <p>{{ article.body }}</p>
                      <div class="post-options">
                        <div class="row">
                          <div class="col-6">
                            <ul class="post-tags">

                              {% if is_liked %}
                              <li><a onclick="like('{{ article.slug }}', '{{ article.id }}')"><i id="like" style="font-size: 20px" class="fa fa-heart"><span id="count">{{ article.likes.all.count }}</span></i></a></li>
                              {% else %}
                              <li><a onclick="like('{{ article.slug }}', '{{ article.id }}')"><i id="like" style="font-size: 20px" class="fa fa-heart-o"><span id="count">{{ article.likes.all.count }}</span></i></a></li>
                              {% endif %}

                            </ul>
                          </div>
                          <div class="col-6">
                            <ul class="post-share">
                              <li><i class="fa fa-share-alt"></i></li>
                              <li><a href="#">Facebook</a>,</li>
                              <li><a href="#"> Twitter</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-12">
                  <div class="sidebar-item comments">
                    <div class="sidebar-heading">
                      <h2>4 comments</h2>
                    </div>
                    <div class="content">
                      <ul>
                        {% for comment in article.comments.all %}
                          {% if comment.parent == None %}
                            <li>
                              {% if comment.user.profile.image %}
                                 <div class="author-thumb">
                                   <img src="{{ comment.user.profile.image.url }}" alt="">
                                 </div>
                              {% else %}
                                 <div class="author-thumb">
                                   <img src="{% static "images/download.png" %}" alt="">
                                 </div>
                              {% endif %}
                              <div class="right-content">
                                <h4>{{ comment.user.get_full_name }}<span>{{ comment.created_at }}</span></h4>
                                <p>{{ comment.body }}</p>
                                <button onclick="set_value({{ comment.id }})" class="btn btn-primary">Reply</button>
                              </div>
                            </li>
                              {% for reply in comment.replies.all %}
                                 <li class="replied">
                                    {% if reply.user.profile.image %}
                                      <div class="author-thumb">
                                        <img src="{{ reply.user.profile.image.url }}" alt="">
                                      </div>
                                    {% else %}
                                        <div class="author-thumb">
                                          <img src="{% static "images/download.png" %}" alt="">
                                        </div>
                                    {% endif %}
                                      <div class="right-content">
                                        <h4>{{ reply.user.get_full_name }}<span>{{ reply.crated_at }}</span></h4>
                                        <p>{{ reply.body }}</p>
                                      </div>
                                  </li>
                              {% endfor %}
                          {% endif %}
                        {% endfor %}

                      </ul>
                    </div>
                  </div>
                </div>

              {% if request.user.is_authenticated %}
                <div class="col-lg-12">
                  <div class="sidebar-item submit-comment">
                    <div class="sidebar-heading">
                      <h2 id="your_comment">Your comment</h2>
                    </div>
                    <div class="content">
                      <form id="comment" action="#" method="post">
                          {% csrf_token %}
                        <div class="row">
                          <input type="hidden" id="parent_id" name="parent_id" value="">
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="body" rows="6" id="body" placeholder="Type your comment" required=""></textarea>
                            </fieldset>
                          </div>

                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Submit</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              {% endif %}

              </div>
            </div>
          </div>
          {% include "includes/sidebar.html" %}
        </div>
      </div>
    </section>
<script>

    function set_value(id){
        document.getElementById("parent_id").value = id;
        window.location.href = "#your_comment"
    }
</script>

{% endblock %}

blog/templates/blog/contact_us.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Contact Us
{% endblock %}
{% block content %}

    <!-- Page Content -->

    <section class="contact-us">
      <div class="container">
        <div class="row">

          <div class="col-lg-12">
            <div class="down-contact">
              <div class="row">
                <div class="col-lg-8">
                  <div class="sidebar-item contact-form">
                    <div class="sidebar-heading">
                      <h2>Send us a message</h2>
                    </div>
                    <div class="content">
                      <form id="contact" action="" method="post">
                          {% csrf_token %}
                        <div class="row">
                          <div class="col-lg-12">

                          {{ form }}

                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Send Message</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-12">
            <div id="map">
              <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>

        </div>
      </div>
    </section>


{% endblock %}

blog/templates/blog/message_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</body>
</html>

blog/templates/blog/message_list.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Contact Us
{% endblock %}
{% block content %}

    <!-- Page Content -->

    <section class="contact-us">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="down-contact">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="sidebar-item contact-form">
                                    <div class="sidebar-heading">
                                        <h2>Send us a message</h2>
                                    </div>
                                    <div class="content">
                                        {% for m in message_list %}
                                            <p>{{ m.title }} - {{ m.text | truncatewords:10 }} - {{ m.age }} <span><a href="{% url "blog:message_edit" m.id %}" class="btn btn-primary">Edit</a></span></p>
                                            <hr>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed"
                                width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>

            </div>
        </div>
    </section>


{% endblock %}

blog/templates/blog/message_update_form.html
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    Contact Us
{% endblock %}
{% block content %}

    <!-- Page Content -->

    <section class="contact-us">
      <div class="container">
        <div class="row">

          <div class="col-lg-12">
            <div class="down-contact">
              <div class="row">
                <div class="col-lg-8">
                  <div class="sidebar-item contact-form">
                    <div class="sidebar-heading">
                      <h2>Send us a message</h2>
                    </div>
                    <div class="content">
                      <form id="contact" action="" method="post">
                          {% csrf_token %}
                        <div class="row">
                          <div class="col-lg-12">

                          {{ form }}
                              <a href="{% url "blog:message_delete" object.id %}" class="btn btn-danger">Delete</a>

                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-button">Update</button>
                            </fieldset>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-12">
            <div id="map">
              <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>

        </div>
      </div>
    </section>


{% endblock %}

blog/templates/blog/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for user in object_list %}
        <p>{{ user.get_username }}</p>
    {% endfor %}
</body>
</html>